### ISSUE TITLE
Problems running on android 31+

### ISSUE THREAD

**Issue by jacky4566** [kai-morich/SimpleUsbTerminal#47]
I just tried to compile this app with Android Studio 2021.2.1. The app runs however when connecting to a device it crashes with a few permissions errors:

Not sure exactly what causing this. Your app should request permissions properly from reading android documentation. 

```
java.lang.SecurityException: User has not given 10452/de.kai_morich.simple_usb_terminal permission to access device /dev/bus/usb/001/002
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
        at android.os.Parcel.createException(Parcel.java:2410)
        at android.os.Parcel.readException(Parcel.java:2393)
        at android.os.Parcel.readException(Parcel.java:2335)
        at android.hardware.usb.IUsbManager$Stub$Proxy.openDevice(IUsbManager.java:1022)
        at android.hardware.usb.UsbManager.openDevice(UsbManager.java:719)
...
```

```
    java.lang.IllegalArgumentException: de.kai_morich.simple_usb_terminal: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at de.kai_morich.simple_usb_terminal.TerminalFragment.connect(TerminalFragment.java:275)
```

**Comment by jacky4566** [comment]
Looking more into this. I got it to work by re-connecting the device. Not an expert opinion but I think your code base could use an update to how android does USB permission now. 

The app should be listening to the UsbManager.ACTION_USB_DEVICE_ATTACHED and UsbManager.ACTION_USB_DEVICE_DETACHED Intents. It should attempt to open the device received from the attached intent.

The error above usually happens when the app tries to re-open the connection to a UsbDevice. When the UsbDevice reconnects it is assigned a new hardware address (Old: /dev/bus/usb/001/002, New: /dev/bus/usb/001/003).

**Comment by kai-morich** [comment]
fixed. While porting from 'Serial USB Terminal' app, one change was overseen
