### ISSUE TITLE
Crash after 40 minutes of background running

### ISSUE THREAD

**Issue by skymoomy** [kai-morich/SimpleUsbTerminal#78]
HI,all:
I use SimpleUsbTerminal-master and make some changes to this project:
1.use usbSerialForAndroid of usb-serial-for-android-master instead of    'com.github.mik3y:usb-serial-for-android:3.8.0'  to support my usb device
2.add some log print

I have encountered a recurring problem, sending command to enable log capture per second, and pressing the HOME key to switch the APP to the background,  the app will run normally for a while。But , after about 40 minutes，the notification icon  will suddenly disappears and the APP crashes.The log is as follows。Please help to check what caused the crash. Thank you

[logcat.zip](https://github.com/user-attachments/files/16866446/logcat.zip)

09-04 17:06:07.994 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:07.994 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:07.994 19715 22289 D SerialInputOutputManager: Read data len=496
09-04 17:06:07.995 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:07.995 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:07.998  2239  2258 W UsageStatsService: Unexpected activity event reported! (de.kai_morich.simple_usb_terminal/de.kai_morich.simple_usb_terminal.MainActivity event : 23 instanceId : 123917032)
09-04 17:06:08.002 19715 22028 D ContentCatcher_injector: Interceptor : notifyActivityDestroy: de.kai_morich.simple_usb_terminal@de.kai_morich.simple_usb_terminal.MainActivity@25653092
09-04 17:06:08.002 19715 22028 D ContentCatcher_catcher: CatcherHolder : mCatcherList size: 0
09-04 17:06:08.003 19715 22028 E ContentCatcherManager: failed to get ContentCatcherService.
09-04 17:06:08.070 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.070 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.070 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.071 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.071 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.071 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.071 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.071 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.071 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.071 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.072 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.072 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.072 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.072 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.072 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.072 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.072 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.073 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.073 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.073 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.073 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.073 19715 22289 D SerialInputOutputManager: Read data len=496
09-04 17:06:08.073 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.073 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.074 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.074 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.074 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.074 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.074 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.074 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.074 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.075 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.075 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.075 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.075 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.075 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.075 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.075 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.076 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.076 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.076 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.076 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.076 19715 22289 D SerialInputOutputManager: Read data len=512
09-04 17:06:08.076 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.076 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.077 19715 22289 D SerialInputOutputManager: Read data len=496
09-04 17:06:08.077 19715 22289 I SerialInputOutputManager: end Step ...
09-04 17:06:08.077 19715 22289 I SerialInputOutputManager: start to Step ...
09-04 17:06:08.080  2239  5873 I ActivityManager: Cancel FGS notification userId: 0 definingUid: 10571 packageName: de.kai_morich.simple_usb_terminal processName:de.kai_morich.simple_usb_terminal ChannelId:de.kai_morich.simple_usb_terminal.Channel foregroundNotiWhen:1725440619564 Notiflags:98
09-04 17:06:08.083  2239  2279 D MediaProjectionManagerServiceStubImpl: handleForegroundServicesChanged
09-04 17:06:08.083  9806  9914 D MyLog   : -->log(1): [Tid:377] [KeepAliveManager] -->onProcessDied(), pid=19715, uid=10571
09-04 17:06:08.084  2239  3986 I MiuiNetworkPolicy: updateUidState uid = 10571, uidState = 10
09-04 17:06:08.086 19715 19715 I SerialInputOutputManager: Stop requested
09-04 17:06:08.086 19715 19715 D CdcAcmSerialDriver: setDTR.mDtr：false
09-04 17:06:08.087 19715 19715 D CdcAcmSerialDriver: setRTS.mRts：false
09-04 17:06:08.087  2239  2239 I NotificationService: Cancel FGS notification CallingUid: 10571 CallingPid: 19715 Pkg: de.kai_morich.simple_usb_terminal Id:1001 Tag:null UserId:0 MustHaveFlags:0 MustNotHaveFlags:0 Reason:8 foregroundNotiWhen:1725440619564 foregroundNotiFlags:98 foregroundNotiChannelId:de.kai_morich.simple_usb_terminal.Channel
09-04 17:06:08.087  2239  3986 I MiuiNetworkPolicyTrafficLimit: updateWhiteListUidForMobileTraffic uid=10571,add=false
09-04 17:06:08.088  2239  3986 D MiuiNetworkPolicyTrafficLimit: updateWhiteListUidForMobileTraffic rst=true
09-04 17:06:08.088 19715 19715 D UsbDeviceConnectionJNI: close
09-04 17:06:08.088 19715 22289 I SerialInputOutputManager: Socket closed
09-04 17:06:08.090 19715 22289 I SerialInputOutputManager: Stopped
09-04 17:06:08.092  5540  5540 D MiuiBubbleManager: onEntryRemoved: com.android.systemui.statusbar.notification.collection.NotificationEntry@9e7cdae
09-04 17:06:08.094  1681  1681 I vendor.qti.hardware.servicetrackeraidl-service: unbindService is called for service : de.kai_morich.simple_usb_terminal/.SerialService and for client de.kai_morich.simple_usb_terminal
09-04 17:06:08.094  1681  1681 I vendor.qti.hardware.servicetrackeraidl-service: size of service connections for service: de.kai_morich.simple_usb_terminal/.SerialServiceafter removal is 0
09-04 17:06:08.094  1681  1681 I vendor.qti.hardware.servicetrackeraidl-service: size of client connections for client: de.kai_morich.simple_usb_terminalafter removal is 0
09-04 17:06:08.094  1681  1681 I vendor.qti.hardware.servicetrackeraidl-service: destroyService is called for service : de.kai_morich.simple_usb_terminal/.SerialService
09-04 17:06:08.095  2239  6716 W ActivityManagerServiceImpl: Sending non-protected broadcast android.intent.action.APPLICATION_MESSAGE_UPDATE from system 5540:com.android.systemui/1000 pkg com.android.systemui. Callers=
09-04 17:06:08.096 19715 19715 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda22@afa620
09-04 17:06:08.097  2239 11183 D CoreBackPreview: Window{b195d40 u0 de.kai_morich.simple_usb_terminal/de.kai_morich.simple_usb_terminal.MainActivity}: Setting back callback null
09-04 17:06:08.098 29372 29462 D IdProviderImpl: getOAID from com.miui.analytics
09-04 17:06:08.099 10730 10839 I Launcher.ApplicationsMessage: onReceive true
09-04 17:06:08.099 10730 10839 I Launcher.ApplicationsMessage: update de.kai_morich.simple_usb_terminal/ to null
09-04 17:06:08.100  5540  9429 D NotificationProvider: call method=canShowFocus extras=Bundle[{package=de.kai_morich.simple_usb_terminal}]
09-04 17:06:08.101 23813 23813 I FOCUS_NOTIFICATION_23813_23813:  packageName = de.kai_morich.simple_usb_terminal hasFocusPermission  =true
09-04 17:06:08.101 23813 23813 I NotifySyncService_23813_23813: onNotificationRemoved reason 8 ,focusExtra = null
09-04 17:06:08.101 23813 23813 I NotifySyncService_23813_23813: onNotificationRemoved appID:de.kai_morich.simple_usb_terminal uid:1001 key:0|de.kai_morich.simple_usb_terminal|1001|null|10571  reason:8
09-04 17:06:08.101 23813 23813 I NotifySyncService_23813_23813: handle MSG_NOTIFY_REMOVE size = 1
09-04 17:06:08.105  2239 11183 W InputManager-JNI: Input channel object 'b195d40 de.kai_morich.simple_usb_terminal/de.kai_morich.simple_usb_terminal.MainActivity (client)' was disposed without first being removed with the input manager!
09-04 17:06:08.109  1842  2196 D MI-SF   : mIsSupportAutomodeForMaxFpsSetting is 1(1), getCurrentBrightness() = 1061(528), mIsKeepAutoMode 0
09-04 17:06:08.110  1842  2196 D RefreshRateSelector: fixedMode_group: 41434112, isFindModeGroup 1
09-04 17:06:08.110  1842  2196 D RefreshRateSelector: find max refresh rate:120, mode Group:41434112
09-04 17:06:08.110  1842  2196 E DisplayDevice: setDesiredActiveMode : Idle status skip setActiveMode, isDdicIdleMode: 1
09-04 17:06:08.120  2644  2681 E misight_perf:  [902001001, de.kai_morich.simple_usb_terminal, 19715, long running]
09-04 17:06:08.120  2239  3986 I MiuiNetworkPolicy: updateUidState uid = 10571, uidState = 18
09-04 17:06:08.121  2644  2660 I misight : OnEvent EventPrivacyCompliance event=902001001
09-04 17:06:08.122  2644  2681 W misight_perf:  [902001300, de.kai_morich.simple_usb_terminal, 19715, service oncreate latency]
09-04 17:06:08.122  2644  2660 I misight : OnEvent EventStorageManager event=902001001,2
09-04 17:06:08.124  1842  1842 D MI-SF   : mIsSupportAutomodeForMaxFpsSetting is 1(1), getCurrentBrightness() = 1061(528), mIsKeepAutoMode 0
09-04 17:06:08.124  1842  1842 D RefreshRateSelector: fixedMode_group: 41434112, isFindModeGroup 1
09-04 17:06:08.124  1842  1842 D RefreshRateSelector: find max refresh rate:120, mode Group:41434112
09-04 17:06:08.124  1842  1842 D MI-SF   : mIsSupportAutomodeForMaxFpsSetting is 1(1), getCurrentBrightness() = 1061(528), mIsKeepAutoMode 0
09-04 17:06:08.124  1842  1842 D RefreshRateSelector: fixedMode_group: 41434112, isFindModeGroup 1
09-04 17:06:08.124  1842  1842 D RefreshRateSelector: find max refresh rate:120, mode Group:41434112
09-04 17:06:08.124  1646  2181 I SDM     : HWCDisplay::SetActiveConfigWithConstraints: config: 3, WxH 1440x3200, fps 120
09-04 17:06:08.125  1646  2181 W SDM     : HWDeviceDRM::GetSupportedBitClkRate: Requested rate not supported: 1360000000
09-04 17:06:08.126  1646  2181 I SDM     : HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1440x3200-1 for Peripheral
09-04 17:06:08.126  1646  2181 I SDM     : HWCDisplay::SubmitDisplayConfig: Active configuration changed from config 6 to 3
09-04 17:06:08.126  1646  2181 I SDM     : HWCDisplay::SubmitDisplayConfig: Active WxH 1440x3200, timing_fps: 120, sf_fps: 120,ddic_mode:2
09-04 17:06:08.127  1646  2357 I vendor.qti.hardware.display.composer-service: Sensor: notify citsensorservice to trigger cwb, misForced = 0
09-04 17:06:08.127  2937  4129 I libsensor-parseRGB: request dump start for mRequestDisplayId 0
09-04 17:06:08.127  2937  4129 D vendor.xiaomi.sensor.citsensorservice.aidl: handle id:10 wxh:1536x3200 uwxuh:1440x3200 size: 14745600 fd:18 fd_meta:19 flags:0x228 usage:0x33  format:0x3 layer_count: 1 reserved_size = 0
09-04 17:06:08.130  1744  1926 D FPSMonitor: threadFuncFpsMonitor display 0, fps 212060
09-04 17:06:08.148  2644  2660 I misight : OnEvent EventInfoPack event 902001001
09-04 17:06:08.149  2644  2660 I misight : OnEvent EventPrivacyCompliance event=902001300
09-04 17:06:08.149  2644  2660 I misight : OnEvent EventStorageManager event=902001300,2
09-04 17:06:08.157  1842  1842 D MI-SF   : [FpsStat] distroy...
09-04 17:06:08.172  2644  2660 I misight : OnEvent EventInfoPack event 902001300
09-04 17:06:08.183  2937  2981 E libsensor-parseRGB: CWB NotifyCWBBufferDone  error 0
09-04 17:06:08.190  2239  2258 I ThermalObserver: Temperature control has been released.
09-04 17:06:08.246  2239  6092 I NetworkAccelerateSwitchService: EVENT_RSSI_POLL. mRssiPoll=true
09-04 17:06:08.286  2239  3987 E WifiScoreReportInjector: current network is in roaming environment
09-04 17:06:08.287  2239  6092 I NetworkAccelerateSwitchService: getAverageWifiRssi:56
09-04 17:06:08.287  2239  6092 I NetworkAccelerateSwitchService: checkRssiChange mMovementState:0 mMovement:false
09-04 17:06:08.338  2644  2681 E misight_perf:  [902001050, surfaceflinger, 0 long running]
09-04 17:06:08.340  2644  2660 I misight : OnEvent EventPrivacyCompliance event=902001050
09-04 17:06:08.340  2644  2660 I misight : OnEvent EventStorageManager event=902001050,2
09-04 17:06:08.341  2644  2660 I misight : DetectDropByTime event 902001050 over hour cnt drop it, hourCnt=8 halfCnt=3, maxCnt=200
09-04 17:06:08.343  1842  2196 D MI-SF   : setIdleFps choose FPS:60, mode:20711936
09-04 17:06:08.346  2644  2660 I misight : OnEvent EventInfoPack event 902001050
09-04 17:06:08.352  1646  2181 I SDM     : HWCDisplay::SetActiveConfigWithConstraints: config: 6, WxH 1440x3200, fps 60
09-04 17:06:08.353  1646  2181 W SDM     : HWDeviceDRM::GetSupportedBitClkRate: Requested rate not supported: 1360000000
09-04 17:06:08.353  1646  2181 I SDM     : HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1440x3200-1 for Peripheral
09-04 17:06:08.354  1646  2181 I SDM     : HWCDisplay::SubmitDisplayConfig: Active configuration changed from config 3 to 6
09-04 17:06:08.354  1646  2181 I SDM     : HWCDisplay::SubmitDisplayConfig: Active WxH 1440x3200, timing_fps: 60, sf_fps: 60,ddic_mode:1
09-04 17:06:08.355  1646  2357 I vendor.qti.hardware.display.composer-service: Sensor: notify citsensorservice to trigger cwb, misForced = 0
09-04 17:06:08.356  2937  4129 I libsensor-parseRGB: request dump start for mRequestDisplayId 0
09-04 17:06:08.356  2937  4129 D vendor.xiaomi.sensor.citsensorservice.aidl: handle id:10 wxh:1536x3200 uwxuh:1440x3200 size: 14745600 fd:18 fd_meta:19 flags:0x228 usage:0x33  format:0x3 layer_count: 1 reserved_size = 0
09-04 17:06:08.356 19715 19715 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-04 17:06:08.358 19715 19715 E AndroidRuntime: FATAL EXCEPTION: main
09-04 17:06:08.358 19715 19715 E AndroidRuntime: Process: de.kai_morich.simple_usb_terminal, PID: 19715
09-04 17:06:08.358 19715 19715 E AndroidRuntime: java.lang.IllegalStateException: Fragment TerminalFragment{f179858} (2df37ac1-86b2-4d2d-bf91-ede7cb7936b3) not attached to a context.
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at de.kai_morich.simple_usb_terminal.TerminalFragment.status(TerminalFragment.java:509)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at de.kai_morich.simple_usb_terminal.TerminalFragment.sendHeartBeat(TerminalFragment.java:422)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at de.kai_morich.simple_usb_terminal.TerminalFragment.access$100(TerminalFragment.java:58)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at de.kai_morich.simple_usb_terminal.TerminalFragment$1.handleMessage(TerminalFragment.java:100)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:224)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:318)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8759)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
09-04 17:06:08.358 19715 19715 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
09-04 17:06:08.359  1744  1926 D FPSMonitor: threadFuncFpsMonitor display 0, fps 106010
09-04 17:06:08.359 19715 19715 W le_usb_terminal: type=1400 audit(0.0:195470): avc:  denied  { search } for  name="miuilog" dev="dm-51" ino=972 scontext=u:r:untrusted_app:s0:c59,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=de.kai_morich.simple_usb_terminal
09-04 17:06:08.359 19715 19715 W le_usb_terminal: type=1400 audit(0.0:195471): avc:  denied  { search } for  name="miuilog" dev="dm-51" ino=972 scontext=u:r:untrusted_app:s0:c59,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=de.kai_morich.simple_usb_terminal
09-04 17:06:08.359 19715 19715 W le_usb_terminal: type=1400 audit(0.0:195472): avc:  denied  { search } for  name="miuilog" dev="dm-51" ino=972 scontext=u:r:untrusted_app:s0:c59,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=de.kai_morich.simple_usb_terminal
09-04 17:06:08.359 19715 19715 W le_usb_terminal: type=1400 audit(0.0:195473): avc:  denied  { search } for  name="miuilog" dev="dm-51" ino=972 scontext=u:r:untrusted_app:s0:c59,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=de.kai_morich.simple_usb_terminal
09-04 17:06:08.359 19715 19715 W le_usb_terminal: type=1400 audit(0.0:195474): avc:  denied  { search } for  name="miuilog" dev="dm-51" ino=972 scontext=u:r:untrusted_app:s0:c59,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=de.kai_morich.simple_usb_terminal
09-04 17:06:08.364 19715 19715 W ScoutUtils: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
09-04 17:06:08.366  9098 10735 W MQSEventManager: jeoccur
09-04 17:06:08.373  2239 27199 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-04 17:06:08.374  9098  9387 D DigestGenerator: digest=============de.kai_morich.simple_usb_terminaljava.lang.IllegalStateException: Fragment TerminalFragment{XX} (XX-XX-XX-XX-XX) not attached to a context.
09-04 17:06:08.374  9098  9387 D DigestGenerator: at androidx.fragment.app.Fragment.requireContext(Fragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at androidx.fragment.app.Fragment.getResources(Fragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at XX.kai_morich.simple_usb_terminal.TerminalFragment.status(TerminalFragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at XX.kai_morich.simple_usb_terminal.TerminalFragment.sendHeartBeat(TerminalFragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at XX.kai_morich.simple_usb_terminal.TerminalFragment.access$XX(TerminalFragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at XX.kai_morich.simple_usb_terminal.TerminalFragment$.handleMessage(TerminalFragment.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at android.os.Handler.dispatchMessage(Handler.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at android.os.Looper.loopOnce(Looper.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at android.os.Looper.loop(Looper.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at android.app.ActivityThread.main(ActivityThread.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at java.lang.reflect.Method.invoke(Native Method)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
09-04 17:06:08.374  9098  9387 D DigestGenerator: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
09-04 17:06:08.375  2239  2258 W RescuePartyPlus: This device support and enable RescuePartyPlus! (Via cloud control)
09-04 17:06:08.376  2239  2279 I ActivityManager: Showing crash dialog for package de.kai_morich.simple_usb_terminal u0
09-04 17:06:08.377  9098  9387 W MQSEventManager: begin to storeEvent
09-04 17:06:08.378 19715 19715 I Process : Process is going to kill itself!
09-04 17:06:08.378 19715 19715 I Process : java.lang.Exception
09-04 17:06:08.378 19715 19715 I Process : 	at android.os.Process.killProcess(Process.java:1356)
09-04 17:06:08.378 19715 19715 I Process : 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:174)
09-04 17:06:08.378 19715 19715 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
09-04 17:06:08.378 19715 19715 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
09-04 17:06:08.378 19715 19715 I Process : 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
09-04 17:06:08.379 19715 19715 I Process : Sending signal. PID: 19715 SIG: 9

**Comment by kai-morich** [comment]
the `SerialService` queues all data while in background and shows it in the Text view when the App gets visible again.
The App might have been crashed with out of memory. 
Showing very large text is incredibly slow, so don't do it.
If your main purpose is logging, you should write to a file in `SerialService.onSerialRead` and limit the queue size to show only the last data.
